### ISSUE TITLE
Review and test template

### ISSUE THREAD

**Issue by z-y-huang** [gentzkow/template#21]
Hi all,

The goal of this issue is for all assignees to:

1. Read through the [RA manual](https://github.com/gentzkow/template/wiki/Introduction)
2. Check out a clean copy of `template`
3. Following the RA manual and setup instructions in `README.md`, build the repository from start to finish
4. Test `template` and attempt to break it; report any bugs or errors
5. Provide feedback and identify room for improvement

Note that the current example scripts are pretty lacking and one of the items on our todos is to flesh them out to be more comprehensive. Let me know if you have any ideas here!

**Comment by z-y-huang** [comment]
Changes implemented:
- Added `run_all.py` so repository can be built with a single script
- Migrated code in `make.py` scripts to `gslab_make` library to reduce clutter
- Cleaned up traceback for Python 3
- Added more description to error messages

**Comment by z-y-huang** [comment]
Changes implemented:

* Added `run_module` function to clean up `run_all.py` script
* Added `copy_file` to facilitate exporting output locals

**Comment by DavidRitzwoller** [comment]
no progress in past 2 weeks

**Comment by DavidRitzwoller** [comment]
no progress in past 2 weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by DavidRitzwoller** [comment]
no progress in past two weeks

**Comment by gentzkow** [comment]
Another infinite loop.

You should just close this one if you don't have time to do the testing.

>

**Comment by DavidRitzwoller** [comment]
Thanks @gentzkow. @mengsongouyang and I completed initial rounds of testing this summer. @z-y-huang is there anything in particular you would like us to look at?

**Comment by z-y-huang** [comment]
@DavidRitzwoller:

I'll close this for now--currently implementing some changes, but may recruit you all again once those are finished.

Summary:
First round of review by GSLab RAs. Incorporated feedback regarding repository structure and workflow.
