### ISSUE TITLE
Update template with real example

### ISSUE THREAD

**Issue by gentzkow** [gentzkow/template#23]
Revise the template with a live example that provides a good illustration of how our code works in practice.

Example should ideally:
1. Illustrate all the key steps we'd have in a typical project
2. Provide best practice templates for code files, paper / slides, etc.
3. Be as simple as possible subject to achieving (1) and (2)
4. Be readable & fun

I would suggest that we base the example on the "tv & potato chips" example in [code & data](http://web.stanford.edu/~gentzkow/research/CodeAndData.pdf). The /data/ and /analysis/ subdirectories can follow roughly the structure shown on p. 16 of the guide. This will provide a nice link between the two. Don't worry about following what's in code & data religiously. After we lock in the template we can do a round of revision on code & data, updating it to match what we develop here.

I would also suggest that we make the base template use *only* Python and Latex (no Stata / R / Lyx). We should write pretty Python code using the standard data science tools (numpy, pandas, matplotlib, etc.). This is a good time to invest in establishing a Python code template that we like and will want to follow; you might browse some of the big tutorial sites like software carpentry, etc. and choose a good model to follow.

We will then open a new task to create a top level directory called /extensions/ which contains subdirectories called /stata/, /r/, /lyx/, etc. Each of these will be an example module showing best practice for the given software tool and also including any additional setup files, documentation, etc. that we need for that tool.

Minor note: Let's skip the step in code & data of having the raw data in Excel format. Let's put the raw data directly in csv format instead.

**Comment by z-y-huang** [comment]
Added example scripts in accordance to "TV & potato chips" example. Add explanation & documentation.

**Comment by Houdanait** [comment]
@gentzkow maybe we can close this issue ? the `tv` and `chips`example does run in the template

**Comment by gentzkow** [comment]
agreed

>

**Comment by Houdanait** [comment]
**Summary of this issue**

The goal of this issue was to add a real example that could be run in the template within the full pipeline, to build, clean and make a plot on two csv  datasets ` tv.csv `and `chips.csv`.

This was added  and merged to the template in PR #28

**Comment by Houdanait** [comment]
@gentzkow unfortunately I do not have rights to close issues on your template, would it be possible for you to give me rights so I can also edit the template README cf. #36  ?

**Comment by Houdanait** [comment]
**Summary of this issue**

The goal of this issue was to add an example to the template that can be run within the full pipeline. This was implemented via the build, clean and plot of two csv `chips.csv` and `tv.csv `. 

Changes were merged to master in PR #28.
