### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by gentzkow** [gentzkow/template#24]
It occurs to me that we should add a standard open source license to the readme for the template now that it is public.

Can you review the options for that and make a recommendation? We want to allow others to use and modify freely but require them to acknowledge us as the source.

**Comment by z-y-huang** [comment]
@gentzkow:

I reviewed the different options for an open source license (using this [site](https://choosealicense.com/licenses/) for reference) and have listed the two I would recommend. The main difference between the two is mostly just if we want to require that any derivative software also be open source. 

1. Apache 2.0
   - Requires preserving original copyright and license notices
   - Grants patent rights to users that is rescinded if they engage in patent litigation

2. GNU GPLv3 
   - Requires preserving original copyright and license notices
   - Grants patent rights to users that is rescinded if they engage in patent litigation
   - Any derivative software must also be open source

The most common open source license that people use is the MIT license. The Apache 2.0 license is [basically just a wordier version that is more explicit about patent rights to prevent patent trolling](https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/).

**Comment by gentzkow** [comment]
Great. Thanks! Let's just use the MIT license. I think the chance of patent
litigation involving our repo is remote enough that we can forget about
that.

**Comment by z-y-huang** [comment]
Summary:

Added MIT license to repository.
