### ISSUE TITLE
Plan external data versioning for completed projects

### ISSUE THREAD

**Issue by jcconway** [gentzkow/template#33]
The goal of this issue is to investigate options and decide on suggested best practices for archiving the specific version of external files used at key points in a project. Some possibilities for implementation include:
- creating a .zip file storing the particular version of files used for say the accepted version of a paper, to be stored on Dropbox/Oak/Github
- any file versioning/release features that may be available within Dropbox, if they exist

Successful completion of this issue would include suggested best practices that would ensure replicability of project's analysis at a key point in time, while minimizing data storage costs to the extent possible.

**Comment by jcconway** [comment]
@zkashner I'm assigning this task to you to think about and investigate, as suggested by MG. I'm happy to talk through this task in more detail during our planned meeting on Monday.

**Comment by zkashner** [comment]
@jcconway I would also like to flag that Dropbox, or at least our paid version of Dropbox, has version control integrated. The way that it works is that for any given file you can see the change history, and you are free to restore any past version of any file. I believe in our current Dropbox setup this is limited to the past 180 days, although according to this more in depth [page](https://help.dropbox.com/files-folders/restore-delete/version-history-overview) it is possible to pay for this capability for 10 years, which ought to be sufficient. 
The current way that I have restored old versions is rather cumbersome and involves using the Dropbox GUI and manually restoring each file which over-writes the current version across all installs. I plan to look into whether there is some way to automate this or improve on this process. However, notably--this provides some of the functionality we are looking for.

**Comment by jcconway** [comment]
Thanks @zkashner! This is good to know. I think it would be helpful if your summary for this issue could include the cost of this functionality (ie extending to 10 years of versioning) along with your recommendation for what you think is the best option to pursue.

**Comment by zkashner** [comment]
@jcconway I will get in touch with the help center and get back with that, because it is not immediately obvious to me where to find the pricing. I believe we currently (through looking through assorted files' version history) have at least a year of version history, although that would likely not be sufficient for some of these longer term projects.

**Comment by zkashner** [comment]
@jcconway good news! We are currently on an "unlimited version history package" so we are already paying for this feature. I believe that, with that taken into account, we are best off using that functionality and working to implement a plan to avoid cumbersome manual reversions.

**Comment by jcconway** [comment]
@zkashner good to know! I agree that works as a version history. Do you know if there is a way to tag particular snapshots of the data (e.g., analogous to Github releases)? Ie would there be an easy way within Dropbox's version history to get back to the version of the data that existed at the time of a paper submission?

**Comment by zkashner** [comment]
@jcconway, that is a good question. I am going to ask if you can "tag" them. With further research, I have discovered that Dropbox does this for us with it's [rewind feature](https://help.dropbox.com/files-folders/restore-delete/rewind). You can revert an entire repository to how it looked at any point in time within its version history!

I am not certain if there is a way to do this, but simply cross-referencing the time of the last run for that submission on GitHub. That could in fact be simpler because it would not rely upon remembering to do two separate "releases" at the time of submission.

**Comment by jcconway** [comment]
Thanks @zkashner! "Rewind" sounds like it accomplishes what we want, and it's great to hear that we wouldn't have to separately revert each file. If we are able to rewind to files as they exist at a certain time, cross-referencing with Github commit times then seems like it would accomplish what we want reasonably well. (Minor possibility of file changes between when a repo is run vs. committed, but likely not a major concern.) I would be fine with this solution.

**Comment by zkashner** [comment]
@jcconway I got a response from Dropbox

> Following up on our chat and your question of tagging points in time in case you need to rewind thank you for this feature request I will make sure to pass your feedback along to our development team.

So, currently there is no way of tagging points in time, but they took my question as a "feature request" so it may at some point in time be implemented. I will work on documenting this. My first thought of where to note these findings would be within the [Paper Production](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production) section, which I would have expected to have some sort of notes on the release procedure. 

Jacob, do you have any objections to me adding to the RA manual regarding adding tagged releases and documenting this solution there?

**Comment by jcconway** [comment]
@zkashner I'd suggest that you write up a brief proposal of your solution for MG as a comment here, prior to changing the RA manual. If he's on board with this plan, then we could go ahead and implement those changes in the RA manual.

**Comment by zkashner** [comment]
@gentzkow here is the proposed solution we have to this problem of data versioning.

Our Dropbox account allows for unlimited version history, and Dropbox's [rewind feature](https://help.dropbox.com/files-folders/restore-delete/rewind) allows you to revert an entire repository to how it looked at any point in time within its version history. Currently, there is no way to "tag" these as we do on GitHub, but they took that question as a feature request, so there may be at some point in the future.

The proposed resolution is to make a note in the RA manual, potentially in the Paper Production section, about the process of releasing. In this, I would also note that to revert the Dropbox repository to the state it was for the release we can simply "rewind" to the point in time of this release using Dropbox's web-based interface. 

Would you be alright with us adding information about releases to the RA manual and the following solution?

**Comment by gentzkow** [comment]
@zkashner Sorry for the slow reply here. Your plan using Dropbox rewind sounds good to me. I think we should create a new page in the RA manual after "Papers & Slides" and before "Production" called "Releases." It can include complete instructions for releases including the case where we're just posting a PDF for a paper or talk as well as the case where we are releasing data to Dropbox. 

One question: Do we have a current procedure for dealing with the following cases?

(1) Repository produces intermediate data files that are too big to be versioned in Github. E.g., module A in the repo produces /moduleA/output/data/ whose contents are very large; module B in the same repo depends on /moduleA/output/data/ as an input.

(2) Repository X produces output that is then used by Repository Y as an input. 

Both of these seem to me like situations where we would want to release data to Dropbox. Maybe we can write a protocol for these cases into the Releases RA manual page. I think it would be a good idea if @zkashner could survey some of the past RAs -- e.g., Zong, David, Linda -- to get a sense of the strategies we've been using to deal with this in the past.

**Comment by zkashner** [comment]
@gentzkow no worries! To your questions, I have not encountered any protocol regarding these cases, nor have I ever run into those cases myself. I will gladly survey the past RAs to ensure that the release page is as comprehensive as possible!

**Comment by zkashner** [comment]
@gentzkow I am circling back to this, and seeking to begin writing the release page. I believe that I do not currently have write access to [your RA manual](https://github.com/gentzkow/ra-manual), or at least its wiki. Do you think you could please invite me to that repository? Thanks!

**Comment by zkashner** [comment]
@gentzkow I spoke to past RAs, mainly David, about those questions above. Here are the answers:

1. In the PhoneAddiction data pipeline we encounter this and use `rclone sync` and store the intermediate output on Dropbox. My intuition is that the only projects with this large of files must be run on cluster computers like Sherlock. It seems as though this updating procedure is managed in the sbatch files scheduling jobs.  
2. Per David, In the past the solution to this was also to use `rclone sync` to ensure that the inputs were up to date. In the RA manual page I recommend using output from releases whenever possible, although in some cases the work between repositories surely informs one another and continuous syncing is necessitated. 

For both, it is possible to create some tool to wrap these functions, however I think that the current protocol is quite good and `rclone` is not very complex.

Also, I have finished up writing the RA manual page and will gladly add it when I have access!

**Comment by gentzkow** [comment]
@zkashner I added you to the ra manual repo. Sounds like the best next step is for you to add that page then for me to review the protocol as described there. Thanks!

**Comment by zkashner** [comment]
@gentzkow sounds good! I just added [here](https://github.com/gentzkow/ra-manual/wiki/Releases).

**Comment by jcconway** [comment]
Thanks @zkashner! I read through the [wiki](https://github.com/gentzkow/ra-manual/wiki/Releases), which made sense to me. I looked into "Dropbox Rewind" to ensure that I could implement on my computer if needed. The "Dropbox Rewind" option was available on my personal account, but not on my GSLab account. My guess is that the admin settings (mentioned in the documentation [here](https://help.dropbox.com/files-folders/restore-delete/rewind)) may currently be set such that only GSLab admins can implement a Dropbox Rewind. I'll flag as a question for @gentzkow whether permissions should be set such that all lab members can perform a Dropbox Rewind.

It might also be helpful to link to that Dropbox Rewind documentation (again [here](https://help.dropbox.com/files-folders/restore-delete/rewind)) in an FAQ, as it describes where to find this option within Dropbox.

**Comment by zkashner** [comment]
@jcconway thanks so much for the helpful feedback. I have included the link to Dropbox rewind documentation and defer to @gentzkow about whether doing these rewinds should be the responsibility of the super-RA or whether we should change that permission setting.

**Comment by gentzkow** [comment]
Thanks guys. I just changed the setting so everyone on the team should be able to use Dropbox Rewind.

**Comment by gentzkow** [comment]
The RA manual [page](https://github.com/gentzkow/ra-manual/wiki/Releases) looks great. I made edits.

It seems like the current protocol is designed for a case where we are exporting the full contents of a repository at a given commit including all LFS files. A few thoughts on that:

    * In this case, I think we need to be strict that the subdirectory inside /release/ corresponds exactly to a repository name. Otherwise it's not clear what the SHA commit code of the subdirectories it contains corresponds to. 

    * I wonder if there is a more robust way to record provenance information about the repo. E.g., could we add something to the release code that produces a release_readme.txt containing the name, URL, and full commit hash at export (and any other similar info we can easily pull from Git)? I'd think we could do this by just piping output from the relevant git command to text.

    * If we had such a provenance file, I wonder if it wouldn't be better to use a convention where the release subdirectories are named by the date (e.g., "2020_11_05") rather than the hash. This will make it easier to sort the releases by date and it will be more informative for people looking at downstream code referencing the release.

    * I'd like to think about whether we can extend our protocol to allow for cases other than full export of a repository. E.g., (i) we wish to export a single directory or a subset of files not the entire repository; (ii) we wish to export large intermediate data files that are not committed even to LFS (as in the PhoneAddiction example [above](https://github.com/gentzkow/template/issues/33#issuecomment-713851492)). I could see value in (i) not only to save storage space but also to make it clearer to downstream users what the files are. For example, we might have something that looks like:

```
/PhoneAddiction/
    /cleaned_data/
        /2020_11_01/
        /2020_11_07/
        ...
    /full_repo/
        /2020_10_30/
        ...
```

**Comment by jcconway** [comment]
> Thanks guys. I just changed the setting so everyone on the team should be able to use Dropbox Rewind.

Great, I have confirmed that the "Rewind Dropbox" option is now available for me. 

I like MG's other suggestions [above](https://github.com/gentzkow/template/issues/33#issuecomment-722532232). @zkashner I'll let you take the lead on implementing any changes, but I'm available to help/discuss if needed.

**Comment by zkashner** [comment]
@gentzkow that sounds like a great idea, I'll work on implementing these suggestions. I agree that the date sounds like an improvement over the hash codes, and realistically we should be doing at most one release a day, so duplication should not be much of a problem.

**Comment by gentzkow** [comment]
Great. We can always append "b", "c", etc. to dates when we need to do multiples. We should write the code so it won't overwrite if one person tries to release 2020_11_06 and a different person happens to have already released something w/ that date.

**Comment by zkashner** [comment]
@gentzkow, @jcconway  looping back to this:

- I have added the ability (and corresponding directions for how to) copy over just sub-portions of a repo.
- I have added code to the script to create a `release_readme.txt` with the URL, branch name, and full hash code.
- I added a little while back the functionality to encode releases by date (+ letter appended if needed).

If you have any other suggestions/comments I am happy to implement them, otherwise I believe this should be ready to close.

**Comment by jcconway** [comment]
Thanks @zkashner! Overall this looks good to me. 

One minor comment/suggestion: If I understand correctly, the current script makes a release from all files in the current working directory. I can imagine situations in which one might want to include/exclude certain types of files in the release, and so could imagine including a reference in the wiki to [rclone filtering](https://rclone.org/filtering/) for how one might achieve this. I don't view this as crucial, and would be fine closing this issue whenever MG signs off.

**Comment by zkashner** [comment]
@jcconway thanks for the feedback! I added that link.

**Comment by gentzkow** [comment]
Thanks @zkashner. This sounds good to me.

One very minor point: Jesse and I were discussing harmonizing the gentzkow and gslab RA manuals, and one decision we made is that all readmes should be .md rather than .txt. If you could change that here and in our RA manual that would be great.

Otherwise, cleared to wrap this up.

**Comment by zkashner** [comment]
@gentzkow sounds good! I just changed the script so the `release_readme` is a `md` file rather than `txt now. Additionally, I changed any reference to a `readme.txt` in both manuals to `readme.md`. I left references without a file extension as they were.

If that is not what you meant, please let me know!

### Summary

In this issue we figured out a way to version external data for completed projects to reflect that this external data could change at different release times. As a corollary, we formalized and wrote up the process to create releases, as well as how to create replication packages. This can all be seen in [this wiki](https://github.com/gentzkow/ra-manual/wiki/Releases).
