### ISSUE TITLE
Add conda activate step before check_setup.py in README

### ISSUE THREAD

**Issue by gentzkow** [gentzkow/template#44]
Minor: Current instructions in the README direct the user to run `check_setup.py` before running `conda activate`. I would suggest we add the `conda activate` command to step (3) under Setup.

If you agree, please implement.

**Comment by szahedian** [comment]
I agree with this change! I combined the general instructions previously under "Usage" to step 3 of "Setup". If it looks good I'll go ahead and open a PR and merge.

**Comment by gentzkow** [comment]
Yes!
