### ISSUE TITLE
Simplify make.py

### ISSUE THREAD

**Issue by gentzkow** [gentzkow/template#45]
I thought this might be a good time to take a look at the structure of the `make.py` scripts and see if there's any way we can streamline them. 

Here are some comments / questions

1. The "Load GSLab Make" section is awkward. I don't remember what caused us to have such a complicated loading step here. It would be great if we could just say `import gslab_make` at the top. 

2. "Check if running from root to check conda status" is a little obscure. Can we clarify what we're doing here?

3. I don't like "Uncomment for Stata scripts" on line 49. It looks like this is anticipating a situation where we might want to add a `temp` directory at the top level of the module for outputs we don't want to store/commit (something we do often for Stata scripts). But if we're not including that directory in the template better to just delete this. I wonder if it wouldn't be better practice actually to make that directory `output/temp` so the `make.py` script doesn't have to be modified

4. Line 52 should say something like "MAKE LINKS TO INPUT AND EXTERNAL FILES"

Any other improvements you can suggest?

**Comment by gentzkow** [comment]
(5) One thing we could consider would be to move the definition of the default PATHS to `config.yaml`. Then we could remove this from all the `make.py` scripts. In this case we might need to set the location of `gslab_make` explicitly after line 10 so that can be imported without knowing the `PATHS` variable. We could also change lines 35-36 to reference `ROOT/config.yaml` and `ROOT/config_user.yaml` explicitly rather than pulling these from `PATHS`.

**Comment by szahedian** [comment]
(1) @gentzkow I can confirm that the following shorter and sweeter import statement does work:
```
sys.path.append('../lib/gslab_make')
import gslab_make as gs
```
From here, it's a matter of how succinct we want to be. Getting it to one line would just require more time studying the python import system. 

(2) Lines 39-40 check if the conda requirements listed in `conda_env.yaml` have
changed since the last run of any make script. If so, a warning is issued. I'm not sure what the if-statement on line 39 is for; the condition is true when the script is run by `python make.py` or `python run_all.py`. 

(3) This line is a bit strange. Even if `/temp` is unused, I don't think there's harm in leaving that line in, since `gs.clear_dir()` simply creates an empty directory if one doesn't exist, and `/temp` is listed in `.gitignore`. I'm not sure how replacing `/temp` with `/output/temp` changes anything apart from organization. But perhaps that was all you intended for it?

(5) I agree with moving `PATHS` to `config.yaml`, since it's the same across make scripts. I'm thinking the setup sequence could look something like:
1. Load `gslab_make` from hardcoded path to module.
2. Use `gslab_make` to load `PATHS` from `config.yaml` (path to `config.yaml` will also have to be hardcoded). This may require a small change / update to [update_paths()](https://github.com/gslab-econ/gslab_make/blob/27989bff1aee3a5809faa5f65ca717b86994e0b2/gslab_make/make_utility.py#L80-L120) to read from `config.yaml`.

With this setup, lines 35-36 can remain as they are.

**Comment by gentzkow** [comment]
(1) Great. No need to get down to one line. I think we should use replace `..` with `ROOT` in the path to `gslab_make` so things don't break if `ROOT!='..'`. 

(2) Odd. Can you use git blame to figure out where this was added and see what the context was (via the corresponding git issue)? Unless there's a really good reason to have it, I'd vote we just drop this and maybe throw a note on the project outline for gslab_make reminding us we can put this back in if it becomes a problem.

(3) I'd rather not have `make.py` create an empty `/temp/` directory every time it's run. Let's just drop this line and then the user can create `/output/temp` if they want to. Maybe we can add a note to the documentation to the effect that this is the right place to put temp directories. (I think `clear_dir` should leave `/output/temp/` in place if it exists and clear it, so we don't need a separate command for that.)

(5) Great!

**Comment by gentzkow** [comment]
(1) Sure

(2) OK. Doesn't look like anything we felt strongly about then so fine to drop

(3)(a) Great.

(3)(b) Sorry, what I meant is if you call `clear_dir(['output'])` and `/output/temp`  exists it would be cleared but not deleted. Is that right? In any case, I don't think we need to change the behavior of `clear_dir()`. Having it create the directory can be helpful in the opposite case where you do want the temp directory and the code assumes it already exists.

**Comment by szahedian** [comment]
(3b) Hm I just tested `clear_dir()` and nested directories are deleted along with files (looks like it happens [here](https://github.com/gslab-econ/gslab_make/blob/32cb0861ff4c0d813870adfb0fe7238dca228c32/gslab_make/modify_dir.py#L178)). 

Are there scenarios where we'd want `clear_dir()` to fully clear directories? For reference, outside of tests, `clear_dir()` is only called in `data/make.py`, `analysis/make.py`, and `paper_slides/make.py`.

**Comment by gentzkow** [comment]
OK. Got it. Let's not worry about it for now.

The use case in the past had been where you want to have some directory structure in `output` that the code can assume is in place. But it's probably more transparent in that case to have `clear_dir()` just delete everything then add lines to `make.py` to set up those directories explicitly.

**Comment by szahedian** [comment]
> Let's not worry about it for now.

Ok, so for the purposes of this issue I'll just delete [this line](https://github.com/gentzkow/template/blob/66412ea98e0111fe143d44450ba8cdc92c59a396/data/make.py#L49). We can make a note in the Wiki saying that `/output/temp` is the right place for temp files, and that the directory can be created by adding `gs.clear_dir(['output/temp'])` to the make script.

> 5. I agree with moving PATHS to config.yaml, since it's the same across make scripts. I'm thinking the setup sequence could look something like...

I'm going to open an issue in [gslab_make](https://github.com/gslab-econ/gslab_make) to address part (5) of my [earlier comment on this thread](https://github.com/gentzkow/template/issues/45#issuecomment-908931830). I wanted to run the structure by you before I execute.

If we move `PATHS` to `config.yaml`, then we'll need a `gslab_make` function to load `PATHS`. Concretely, we can add a section to `config.yaml` that looks like
```
make_paths:
  root: '..'
  lib: '../lib'
  output_statslog: 'log/output_stats.log'
```
Then we'll add a function to `make_utility.py` very similar to [`update_paths()`](https://github.com/gslab-econ/gslab_make/blob/32cb0861ff4c0d813870adfb0fe7238dca228c32/gslab_make/make_utility.py#L80-L120) to load `make_paths`.

**Comment by gentzkow** [comment]
Thanks!

Sounds good on the first point.

On the second, also looks good. But I don't think we want to define `root` in `config.yaml`. That's something that may vary across modules depending on their location and I like having it explicit in `make.py`. So maybe we put everything else in `config.yaml` and have `root` passed as an argument to the analogue of `update_paths()`?

**Comment by szahedian** [comment]
As I was working on Docker Stata integration, I ran some of the template do-files in `analysis/code/lib` and `data/code/lib`. It seems the `temp` directory, reference to which within make-scripts we agreed to eliminate, was used by these do-files. I have two questions about this.

1. Do we know why Stata and R files are in `code/lib`? Is this simply for organization? I traced these files' creation back to #23, but there isn't too much discussion of the choice in that issue. 
2. Should we keep these Stata and R files / Should we continue supporting them? That is, if one replaces `gs.run_python(PATHS, <python file>)` with `gs.run_stata(PATHS, <do-file>)` in the make-scripts, should the repo run the same?

**Comment by gentzkow** [comment]
Thanks!

(1) We made a decision a while back to use only python scripts in the main template so that it would run out of the box even for users who don't have Stata or R installed. I think we just threw the Stata and R flavors of the scripts into `/lib/` to get them out of the way until we decided on a more permanent solution. I think we should delete them now.


(2) We definitely want to support Stata and R and have `gs.run_stata(PATHS, <do-file>)` work as expected. We just need to think about the best way to incorporate this in the template so we have both (A) the full template can be run out of the box with only Python installed; (B) someone who wants to use Stata or R can easily see how to do that.

One idea I'd had was to create a top-level directory called `/examples/` or `/extensions/` that contains examples of modules beyond what's included in the template itself. This could include example modules for Stata, R, and Matlab scripts, as well as LaTex and potentially other things. We could also use it to include an example module using the `SCons` build software that was part of the old GSLab template. 

If we like that idea we could add to the template `/examples/stata/` and `/examples/r/`.

**Comment by szahedian** [comment]
Makes sense about (1). I've deleted the `lib` subdirectories and relocated those files to `/examples`. 

In my latest commit, I've followed the idea of `/examples/stata` and `/examples/r` mentioned in (2). I think the structure of these directories is intuitive, and I've added a brief explanatory section to the README.

I've copied the code from `/examples` into the main modules and run them. The R scripts ran without issue. The only hiccup with the Stata scripts was a missing function `matrix_to_txt` in `analyze_data.do`. I found a version of this function in a [Github repo](https://github.com/mcaceresb/stata-matrix-tools), and copied the `.ado` file into the repo. The Stata scripts worked after that. 

The repo linked above credits you with `matrix_to_txt` (bottom of `README`). Still, I'm unsure if copying code like this is best practice. 

As written, the code requires `matrix_to_txt`. If we don't want to copy from a Github repo, we could change downstream modules in `/examples/stata` to not use outputs generated by `matrix_to_txt`.

**Comment by szahedian** [comment]
> Our decision is that we want users to store all Stata .ado files locally, right? Including those that we did not write ourselves?

Yes, I believe this is how the template is set up to be used. From the `README`: "We keep all non-base Stata ado files in the lib subdirectory."

Concerning your second point, I moved `matrix_to_txt.ado` and `standardize_env.do` to `/examples/stata/lib`, and added a full description of what to copy over in the `README`.

We definitely could, as you suggest, copy the functions from `gslab_stata` to `/examples/lib/stata`. Another way to do this would be to add `gslab_stata` as a submodule within `/examples/lib/stata`. I'm not sure, though, if the convenience is worth the clutter and possible confusion. And stylistically, I think it makes sense for `.ado` files to be added to `/lib/stata` on an as-needed basis. But if you feel it makes sense for `gslab_stata` functions to be represented in `template` somehow, it's no problem to add them!

**Comment by gentzkow** [comment]
Great. This looks good. Maybe we could just include a link to the `gslab_stata` repo in the part of the documentation where we discuss Stata.

**Comment by szahedian** [comment]
Thanks @gentzkow. In addition to linking `gslab_stata` in the `README`, I renamed `/examples` as `/extensions`, which feels more apt. I also moved the setup scripts for R and Stata packages from `/setup` to `/extensions/setup`.

**Comment by gentzkow** [comment]
Misc comment: Let's go ahead and remove `ondeck.lyx` and `text.lyx` from `/papers_slides/` (and remove the corresponding lines in `make.py` and the associated output files). Those files are more specific to our lab and they're easy to create when needed.

**Comment by gentzkow** [comment]
Another: What about putting separate readmes inside `extensions/r/` and `extensions/stata/`? I think that would be helpful for people who are just browsing the template and may not have read through the main readme fully.

**Comment by szahedian** [comment]
Just took care of `ondeck` and `text`. And thanks for the suggestion of additional `README` files. I've added those as well.

**Comment by szahedian** [comment]
Note to self: Before merging, need to update [Wiki](https://github.com/gentzkow/template/wiki) so that it mentions `/extensions` and related changes.
