### ISSUE TITLE
Testing Docker integration

### ISSUE THREAD

**Issue by szahedian** [gentzkow/template#49]
Following #43 and #47, this issue will test the portability of `docker build` across multiple OS. Tentatively, this should include ARM Mac, x86 Mac, Windows, and Linux machines, per [this comment](https://github.com/gentzkow/template/issues/47#issuecomment-922343173).

**Comment by gentzkow** [comment]
@szahedian Just flagging that this issue seems to be stale. 

Let me know if you think you'll have bandwidth to look at it in the next month. If not we can close and migrate back to the outline.

**Comment by szahedian** [comment]
@gentzkow thanks for the bump. I'm not sure I'll have the bandwidth to complete this in the next month. Can you clarify what you mean by "migrat[ing] back to the outline."

**Comment by gentzkow** [comment]
Sorry that wasn't clear -- I meant we could close the issue and add a note to the outline [here](https://github.com/gentzkow/template/wiki/Project-Outline) that we would revisit it (including a link to this thread).

**Comment by szahedian** [comment]
**Summary:** The objective of this issue was added to the [project outline](https://github.com/gentzkow/template/wiki/Project-Outline) and left for future work.
