### ISSUE TITLE
Conda version and packages conflicts

### ISSUE THREAD

**Issue by Houdanait** [gentzkow/template#50]
Hello @gentzkow 
In updating the` ad-price-drivers` to this template, I noticed that the user may run into several issues due to the multiplicity of packages needed in the conda environment. 

Let me be more specific. 
In the presence of many packages (such as R packages), the common dependencies needed for different packages may run into conflicts in the conda environment. There is ongoing documentation of this error (see [here](https://github.com/conda/conda/issues/9367) or [here](https://stackoverflow.com/questions/57518050/conda-install-and-update-do-not-work-also-solving-environment-get-errors) for instance). 
It turns out that the only things that works in such a case is to downgrade conda, as has been suggested in some comments. 

I was wondering whether we would want to add this to the ReadMe? F
or instance, we could suggest that if a user intends on having several packages in their environment, then it is advised to downgrade Conda by running `conda install conda=4.6.14`. 

This is just a suggestion, and of course looking forward to hearing your opinion on this. 

Tagging @szahedian as we discussed this earlier today!

**Comment by gentzkow** [comment]
Thanks @Houdanait. I think we should avoid downgrading Conda if at all possible. Ideally we should figure out a way to restructure the set of packages we're requiring to avoid this issue.

I guess at worst we can require the user to install some R packages locally (outside of Conda)?

**Comment by Houdanait** [comment]
Hello @gentzkow, thank you for your feedback!
I looked around this morning to see if there was a workaround this, but it seems that you are right and the best solution would be to ask users to install some R-Packages locally. 

We could add to the ReadMe a sentence such as : 

`If your projects requires many packages that may lead to dependencies conflict in your conda environment, we suggest you install some of them locally.`

**Comment by gentzkow** [comment]
Hmm. I'd vote we not add this to the ReadMe. I think we can just address it
for ad-price-drivers however we need to. If it continues to be a persistent
issue we can think about how to better address it in the template.

>

**Comment by Houdanait** [comment]
Ok @gentzkow thank you so much for your feedback! I will close this issue then and keep this in mind for the future and we can comeback to it if needed!

**Comment by Houdanait** [comment]
**Summary of this issue**

I opened this issue to discuss the potential change to the ReadMe to explicit ways to overcome `conda` dependencies conflicts in projects that may involve several packages. 
After discussion on this thread, no change will be implemented, but we may come back to this later if the issue is persistent.
