### ISSUE TITLE
Fix issue with lfs files in child repos

### ISSUE THREAD

**Issue by szahedian** [gentzkow/template#51]
After creating a new repo using the template, we noticed the following error upon cloning:
```
Error downloading object: analysis/output/regression.csv (b98f379): 
Smudge error: Error downloading analysis/output/regression.csv
(b98f379011017bf4300cbf1f96c0be913478cd5794b3e5622fc499cf3be2430e): [b98f379011017bf4300cbf1f96c0be913478cd5794b3e5622fc499cf3be2430e] Object does not exist on the server: 
[404] Object does not exist on the server

Errors logged to /Users/zahedian/Documents/race-in-notes/.git/lfs/logs/20220224T162457.941482.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: analysis/output/regression.csv: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

From [this](https://github.community/t/lfs-support-for-template-repos/122449) thread online, we determined that the cause of the issue is cloning files stored in the template with git-lfs. These files don't properly transfer to a repo created from the template.

In this issue, we seek to correct this issue with repos created from `gentzkow/template`.

**Comment by szahedian** [comment]
@gentzkow from the [git-book page](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) on git-hooks, there is no mention of a `git clone`-specific hook. Stackoverflow posts on this topic don't turn up any satisfactory solutions (e.g. [here](https://stackoverflow.com/questions/10228065/git-hooks-is-there-a-clone-hook?noredirect=1&lq=1) and [here](https://stackoverflow.com/questions/18188933/run-bash-script-after-git-clone?noredirect=1&lq=1)). It seems there is no  plug-and-play solution, only workarounds that resemble a post-clone hook.

Perhaps this is reason to move to your suggestion:
> if we can't solve this w/ a hook it wouldn't be terrible to treat .gitignore parallel to the way we treat config_user.yaml -- we provide a template in /setup/, the user can modify + copy it over, and if they don't the repo defaults to having nothing tracked by git lfs (which I think is what happens automatically if .gitignore doesn't exist).

One question about this. Did you mean `.gitattirbutes` instead of `.gitignore`? I believe the former is the file that instructs `lfs` to handle certain files.

cc @Houdanait

**Comment by gentzkow** [comment]
Thanks @szahedian. Happy to move to my suggestion in that case.

I did mean `.gitattributes`. Sorry about that.

**Comment by szahedian** [comment]
@gentzkow here's an update on this. I've
1. Removed all `lfs`-related lines from [`.gitattributes`](https://github.com/gentzkow/template/blob/aa16968aef84067391527249b7ea4c5c415be521/.gitattributes)
2. Added a script [`/setup/lfs_setup.sh`](https://github.com/gentzkow/template/blob/aa16968aef84067391527249b7ea4c5c415be521/setup/lfs_setup.sh) that appends to `.gitattributes`. This approach seems more [idiomatic](https://stackoverflow.com/questions/60029570/does-git-lfs-track-do-more-than-writing-to-gitattributes) than replacing `.gitattributes` itself. It also allows flexibility if we wanted to change how the template initializes `git lfs`.
3. Add instructions for initializing `git lfs` to [README](https://github.com/gentzkow/template/tree/issue51-fix_lfs)

Let me know if this general approach sounds okay!

**Comment by gentzkow** [comment]
Looks great. Thanks!!
