### ISSUE TITLE
Revise run_all.py 

### ISSUE THREAD

**Issue by jc-cisneros** [gentzkow/template#58]
Make sure the build script runs correctly after following the setup process. [snairdesai](https://github.com/snairdesai) and I both got the same error after running [run_all.py](https://github.com/gentzkow/template/blob/master/run_all.py) on the terminal. The text of the error on the terminal can be seen on [template_build_error terminal.txt](https://github.com/gentzkow/template/files/9115614/template_build_error.terminal.txt).

**Comment by jc-cisneros** [comment]
@szahedian as we discussed, a quick fix would be to add a command to go back to root directory between each run_module command: 

`### RUN SCRIPTS

gs.run_module(root = ROOT, module = 'data')
os.chdir('..')
gs.run_module(root = ROOT, module = 'analysis')
os.chdir('..')
gs.run_module(root = ROOT, module = 'paper_slides')`

**Comment by snairdesai** [comment]
Also noting that in the [setup instructions](https://github.com/gentzkow/template#setup) for the template, users should be prompted to run the `git lfs pull` command after running `./setup/lfs_setup.sh`.

**Comment by jc-cisneros** [comment]
There is one last consideration to keep in mind that @snairdesai helped me sort out. If you are following the regular setup for [command line usage](https://github.com/gentzkow/template/wiki/Command-Line-Usage), make sure you change the shell to Bash. The default shell in newer Mac OS is zsh (see [reference](https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features)).

**Comment by gentzkow** [comment]
@jc-cisneros @szahedian I haven't looked at the error [above](https://github.com/gentzkow/template/issues/58#issue-1304042916) in detail, but if the issue is that `gs.run_module` is dropping the user in the wrong directory when it exits we should fix that in the gslab_make library rather than doing the "[quick fix](https://github.com/gentzkow/template/issues/58#issuecomment-1184919641)" in run_all.py.

**Comment by jc-cisneros** [comment]
Opened an [issue](https://github.com/gslab-econ/gslab_make/issues/52) and a corresponding [PR](https://github.com/gslab-econ/gslab_make/pull/53) in the gslab_make repository. I am closing this issue on the template repository.
