### ISSUE TITLE
Updates to R dependency installations in Conda

### ISSUE THREAD

**Issue by snairdesai** [gentzkow/template#59]
@gentzkow @szahedian 

Following from #53 and #54, [@jc-cisneros](https://github.com/jc-cisneros) and I were playing around with the `gentzkow/template` format to figure out how to install _both_ R and Python dependencies in the **_same `conda` environment_** in a timely fashion. We had previously removed R dependencies altogether following comments ([here](https://github.com/gentzkow/template/issues/54#issuecomment-1122742492) and [here](https://github.com/gentzkow/template/issues/54#issuecomment-1140150610)) from the AEA Data Editor that the `conda` environment was not solving when `/setup/conda_env.yaml` had both R and Python dependencies listed. The fix below should resolve this:

- **Prior to running `conda env create -f setup/conda_env.yaml`, the  user should run `conda config --set channel_priority strict`.** The user can then proceed with `conda activate <project_name>`, and the rest of the template instructions. More on what this is doing under the hood [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html).
     - _Note_: While this is not required, it is considered best practice to prefix any installations of R software (not packages, but the platform itself), with `r-base=<version_name>`. This change can easily be made in `/setup/conda_env.yaml`.
    
----------------------------------------------------------------------------------------------------------------------------------

**The main benefits of this approach are as follows**: 

1. Assuming all standard package dependencies are installable via `conda-forge`, we no longer need to run a separate script to pull dependencies from `/extensions/R`. We will still need to do so for STATA.
2. We do not need to create distinct `conda` environments for R and Python packages - both can be hosted in the same `conda_env.yaml` file. 
3. Individuals running `conda` on MacOS for replication should no longer have major issues solving their environments if both Python and R dependencies are listed.
4. The above fix also solves part of #56 on Docker usage (in particular [this comment](https://github.com/gentzkow/template/issues/56#issuecomment-1151315054)). If we integrate this fix within our Docker container builds, individuals across OS systems should no longer have major issues solving their environments if both Python and R dependencies are listed. [@jc-cisneros](https://github.com/jc-cisneros) is working on implementing this within Docker currently, and will shortly post an update to #56.

**As an example of computational efficiency, I ran this using all of the package dependencies from [`/setup/conda_env.yaml`](https://github.com/gslab-econ/ad-price-drivers/blob/master/setup/conda_env.yaml) in Ad Price Drivers, and the process had completed within 5 minutes.** Without this fix, we could not solve the environment for `/gentzkow/template` (with far fewer R dependencies) within 40 minutes.

If this approach is acceptable, [@jc-cisneros](https://github.com/jc-cisneros) and I can make revisions to the template instructions in the [same file](https://colab.research.google.com/drive/1LsG3FmAqkX4UbyxCBK0FNcNuxi_xqAeQ#scrollTo=n2ywr5y36vrz) as in `gslab-econ/ra_manual` [#18](https://github.com/gslab-econ/ra-manual/issues/18) and issue a PR here.

**Comment by gentzkow** [comment]
@snairdesai Thanks! As I said at our lunch, this is some *awesome* sleuthing on your and @jc-cisneros' part. Green light to proceed.

Can you write a 1 paragraph summary explaining the problem + solution that would be appropriate for me to send the the AER data editor?

**Comment by snairdesai** [comment]
Sounds good! @jc-cisneros and I are working on Docker instructions integrating this fix in #56, and will start on this shortly after.

**Comment by snairdesai** [comment]
@gentzkow I'll be closing out this issue and moving the proposed `conda` revisions to `template` discussed [here](https://github.com/gentzkow/template/issues/59#issue-1335213999) to #62.

Here is the paragraph we might send to the AER data editor:

Previously, we had been using a `miniconda` environment to handle our package installations in Python, and handled package installations for R and Stata separately. Ideally, we would want to move as many installations to a `conda`-like environment as possible in order to efficiently handle version conflicts. However, when we **(a)** listed a large number of Python packages or **(b)** attempted to list both Python and R dependencies simultaneously in our `conda_env.yaml` file, the `conda` environments took an unreasonably long time to solve. We think a potential workaround here is to [set the default `conda` channel configuration to "strict"](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html) (with the command: `conda config --set channel_priority strict`) _prior_ to creating a new environment. In our tests, the `conda` environments now solve much faster, even if a mixture of Python and R dependencies are installed. Moving forward, this would allow us to install all (standard) Python and R dependencies using `conda`. We are working now on integrating this approach within Docker to allow for version comparability across different OS.

**Comment by snairdesai** [comment]
**Summary of this Issue**

In this issue (which follows from https://github.com/gentzkow/template/issues/53 and https://github.com/gentzkow/template/issues/54), @jc-cisneros and I addressed an issue with extended delays in solving `conda` environments which list both Python and R package dependencies. The proposed solution is detailed [above](https://github.com/gentzkow/template/issues/59#issue-1335213999), and a paragraph which can be sent to AER data editor is also [above](https://github.com/gentzkow/template/issues/59#issuecomment-1229007751).

We are moving the proposed revisions in `template` here to #62 and closing this issue.
