### ISSUE TITLE
Update to Python 3.10

### ISSUE THREAD

**Issue by jc-cisneros** [gentzkow/template#65]
The goal of this issue is to update the Python version used in `master`. The steps are the following:

- [x] Build the conda environment with Python 3.10. Per https://github.com/gentzkow/CommitFlex/issues/114#issuecomment-1270855088, the Python version will be commented out in the `setup/conda_env.yaml` file, so that the norm is that the user updates to the latest version. Update the readme file to reflect current setup.
- [x] Run the repository with the updated conda environment. Report any package conflicts that arise (if any).

cc. @gentzkow @snairdesai

**Comment by jc-cisneros** [comment]
The repository ran successfully with Python 3.10. Some considerations to have in mind:
- I extended the logic of https://github.com/gentzkow/CommitFlex/issues/114#issuecomment-1270855088 to packages. To be precise, that means that the norm is that the user installs the latest versions of the packages. The latest working version is commented out.
- If versions are not specified, the process of solving the environment (conda checking for conflicts) takes longer. The instruction to run `conda config --set channel_priority strict` should be added to the template ReadMe to save a nontrivial amount of time (this is already part of our [Proposed Changes](https://colab.research.google.com/drive/1LsG3FmAqkX4UbyxCBK0FNcNuxi_xqAeQ?authuser=1#scrollTo=Z-6BVKqacw1b)).
- I suggest that as a last step in the process, after running the entire repo successfully, the user updates the commented out versions in the `conda_env.yaml` file. Running `conda list` returns the version of all packages being used. I am working to find a way to return only the smallest working subset of those (i.e., the other packages are their dependencies). 
- The version for the `linearmodels` package has not been commented out. This is due to the fact that the latest version of this package does not work with the current code in `template` (see error below).

<img width="937" alt="Screen Shot 2022-10-07 at 11 26 17 AM" src="https://user-images.githubusercontent.com/108437517/194625038-53798200-48ff-4220-a96b-5574c3d8591f.png">

Per https://github.com/gentzkow/CommitFlex/issues/114#issuecomment-1270855660, we should not be using any packages that don't work with 3.10+. As the `linearmodels` is required in `template`, I will work on debugging the error.

@gentzkow @snairdesai I would appreciate your input on the following proposed steps:
- If you agree with the proposed last step in the process (i.e., updating the comments in the `conda_env.file`), I will add this instruction in the [Proposed Changes](https://colab.research.google.com/drive/1LsG3FmAqkX4UbyxCBK0FNcNuxi_xqAeQ?authuser=1#scrollTo=Z-6BVKqacw1b) working document. 
- The [Proposed Changes](https://colab.research.google.com/drive/1LsG3FmAqkX4UbyxCBK0FNcNuxi_xqAeQ?authuser=1#scrollTo=Z-6BVKqacw1b) affect both `template` and the `RA Manual` (`template` references the `RA Manual`). What should be the approach to bringing those changes to these two repositories? @snairdesai and I currently don't have contributor status in `gslab-econ/lab-manual`.

**Comment by snairdesai** [comment]
Thanks @jc-cisneros! For some reason the link you pasted gives me an "invalid credentials" error. It doesn't seem like any updates have been made to our [original shared document](https://colab.research.google.com/drive/1LsG3FmAqkX4UbyxCBK0FNcNuxi_xqAeQ)?

**Comment by snairdesai** [comment]
@jc-cisneros The edits above look good to me, I think we can add to the Proposed Changes document!

**Comment by gentzkow** [comment]
Thanks @jc-cisneros. Proposed changes sound great. 

The `lab-manual` permissions were just a glitch. Everyone in the gslab RA group now has write access (including you!).

**Comment by jc-cisneros** [comment]
Summary:

On this issue, the Python version used by `template` was updated to 3.10. We also decided to add an extra step regarding listing the package version (see https://github.com/gentzkow/template/issues/65#issuecomment-1271955569). 

Changes to master were brought by #66.
