### ISSUE TITLE
Julia extension

### ISSUE THREAD

**Issue by jc-cisneros** [gentzkow/template#67]
In this issue we will test the `run_julia` wrapper from `gslab_make` (see https://github.com/gslab-econ/gslab_make/issues/54).

Task list
- [x] Test if Julia + packages can be added to the conda environment.
- [x] Run Julia scripts from `root` using the `run_julia wrapper`

**Comment by jc-cisneros** [comment]
Update:

As of today, the best strategy to using conda+Julia is the following:
- Add `-julia # =version` to the conda_env.yaml file and create the conda environment.
- Use Conda.jl to add packages to the conda environment (See https://github.com/JuliaPy/Conda.jl)

A way to add the Julia packages within the conda_env.yaml is currently being developed (See https://github.com/conda-forge/conda-forge.github.io/issues/1822)

**Comment by jc-cisneros** [comment]
Summary:

On this issue we tested the compatibility of the current structure of `template` with Julia. Specifically, we installed Julia within the build conda environment workflow and used the `run_julia` with a script that produces a plot. The `run_julia` function worked as expected and [was added to the `gslab_make` master branch](https://github.com/gslab-econ/gslab_make/pull/55). 

Flagging some of the lessons and opportunities for future updates:
- The current Julia extension of `template` does not build the Julia environment using conda-forge, but rather uses Julia's built in Pkg package manager. These can lead to conflicts that not trivial to fix when trying to call Python (or any Python backend) within a Julia script (see https://github.com/gentzkow/template/pull/68#issuecomment-1285951640). There are ongoing developments on conda-forge that might be relevant to include in the future to make the process easier and to leave solving package conflicts to conda (see https://github.com/gentzkow/template/issues/67#issuecomment-1273944247).
- Plots on Julia sit on other backends (see https://docs.juliaplots.org/stable/). Make sure the backends can run non-interactively (eg. GR required us to quit the gksqt program for the `run_all` script to continue and Pyplot led to package conflicts between Python installations in conda).

**Comment by zkashner** [comment]
@jc-cisneros this is an awesome addition! If you are interested, it may be worthwhile to document how this changes the setup process within the README, because this does add some small changes to the setup (i.e. running `julia julia_conda_env.jl` from root).

**Comment by jc-cisneros** [comment]
Thanks @zkashner! Given than the default behavior is not to include `julia`, perhaps we could add the relevant instruction to both the `Running Package Scripts in Other Languages` and `Adding Packages` sections.
