### ISSUE TITLE
Investigate error in `check_setup.py` when freezing dependencies

### ISSUE THREAD

**Issue by jc-cisneros** [gentzkow/template#73]
@zkashner flagged that when he freezes a dependency version in the `conda_env.yaml` file, the current `check_setup.py` script fails to parse the names of the packages correctly. The goal of this issue is to fix that bug.

The steps to be taken are the following:
1. Reproduce the error described above and post it on this issue.
2. Modify `check_setup.py` to be robust to this scenario. @zkashner mentioned he can share a potential solution for this problem.

Thanks @zkashner for flagging this!

**Comment by zkashner** [comment]
@jc-cisneros thanks for making this issue. The solution that I implemented for my own project is to alter the following functions as follows to drop beyond the dependency number
```

def get_python(packages):
    prefixes_python = ('python', 'python=', "pip=", "r=", "r-", "r", "pyyaml", "gitpython")
    python_packages = [item for item in packages['dependencies'] if not 
                       item.startswith(prefixes_python)]
    python_packages = [p.split("=")[0] for p in python_packages]
    return python_packages


def get_r(packages):
    prefixes_r = ("r-")
    r_packages = [item for item in packages['dependencies'] if item.startswith(prefixes_r)] 
    r_packages = [p.split("=")[0] for p in r_packages]
    return r_packages
```
Another small change I needed to make was to alter the for loop within `check_dependencies` to be 
```
# List all R packages which need to be installed.
for package in r_packages:
    package = package.replace('r-r.',"")
    package = package.replace('r-',"")
    output = str(subprocess.run(['Rscript', '-e', f'library("{package}")']))
    if "returncode=0" not in output:
        failed_r_packages.append(package)
```
in order to properly strip `r.utils` to be loaded as `library(utils)` correctly.
I would note that this solution does not have the capacity to check whether the dependencies have the correct version numbers--which could be a future extension.

**Comment by jc-cisneros** [comment]
Thanks @zkashner! Let me first show you an example of this bug on my end to make sure we are talking about the same error. I added an explicit version number for the termcolor package (2.1.0) and installed it. When running, `check_setup.py` the error message states 

```Python
ERROR! The following Python packages were not properly installed: `termcolor=2.1.0`.
```
I believe this error is generated by the nature of the test (you cannot use `import termcolor=2.1.0` in Python). As @zkashner mentioned, his proposed solution would work as we would be back to trying `import termcolor`. I added this solution in [2771507](https://github.com/gentzkow/template/commit/277150708c8da3e763b742f08cfd3a4197f63fa2).

**Comment by zkashner** [comment]
@jc-cisneros that is exactly the bug I was talking about!

**Comment by jc-cisneros** [comment]
@gentzkow @snairdesai my vote would be to use the solution proposed by @zkashner for now. The big limitation is that we would not be able to detect/enforce a specific version that was chosen for any particular reason. Given that the default behavior is to use the latest version available and that we are logging the versions used, this missing feature does not have a major role now.

If you agree, we can move to a quick PR.

**Comment by snairdesai** [comment]
@jc-cisneros Thanks for the work! I’ve just run this on my end for a separate project based on template and can confirm the same error. This solution seems good for now — ideally we make a shift to Docker at some point to overcome the inability to freeze dependencies. For now, the above solution looks good to me. I’ll see if there any other solutions from my end as well.

**Comment by gentzkow** [comment]
Hi guys - I haven't looked at the details of the code, but am I understanding right that this is only a problem w/ `check_setup.py` not a problem with the actual Conda installation? I.e., we can install the packages successfully when we freeze the versions but our own script to verify that they're installed fails?

**Comment by snairdesai** [comment]
@gentzkow I believe that's correct - @jc-cisneros let me know if this is your understanding as well. This means we can't currently catch when users install different versions of these packages, which are distinct from those we specified in `conda_env.yaml`.

**Comment by jc-cisneros** [comment]
@gentzkow @snairdesai you are exactly right. With the proposed solution `check_setup.py` would be able to check that all the packages are installed (even if versions are specified), but would not throw an error if we wanted to enforce a specific version of the package.

**Comment by zkashner** [comment]
@jc-cisneros @snairdesai just to chime in quickly--it should not be so difficult to enforce a specific version. 
My code (as it stands) does not do it, but it would be easy to check which packages specified in the conda environment have associated version numbers. Cross-checking these with `EXAMPLE_PACKAGE.__version__` and `packageVersion(EXAMPLE_PACKAGE)` in python and R respectively ought to be simple.

**Comment by gentzkow** [comment]
Thanks. I don't think it's *super* important that `check_setup.py` check for the specific versions. It would be fine if (i) we can still fix the versions in the setup script and (ii) `check_setup.py` just confirms that the packages are installed.

But if it's easy to throw in those checks let's do so.

**Comment by jc-cisneros** [comment]
## Summary

In this issue we provided a solution to the bug mentioned in https://github.com/gentzkow/template/issues/73#issue-1530308632 and replicated in https://github.com/gentzkow/template/issues/73#issuecomment-1380874648. The current solution satisfies the characteristics described in https://github.com/gentzkow/template/issues/73#issuecomment-1382937861. 

The corresponding PR is https://github.com/gentzkow/template/pull/74.

Thanks @zkashner for flagging this and providing a solution!
