### ISSUE TITLE
Fix dependency issue between rlang and tidyverse in template

### ISSUE THREAD

**Issue by snairdesai** [gentzkow/template#82]
The purpose of this issue is to fix a potential dependency issue in our `conda` environment when building `template` with `R`.

---

### Origin + Description of Bug

While compiling another lab repository with R scripts, I found a bug in `template` arising from the `conda` environment build (@jc-cisneros also confirmed this on his end). See the error message below from my local console session:

<details>

<img width="716" alt="Screen Shot 2023-06-04 at 2 35 01 PM" src="https://github.com/gentzkow/template/assets/63830369/6f56ca01-4e9d-49c3-b1e2-2f9213366852">

<summary>Error message:</summary>
</details>

This error is not thrown for other packages loaded with `conda-forge` (i.e., `lubridate` or `data.table`), and the repository in question was successfully compiling less than a month ago.

---

### Theory + Next Steps

@jc-cisneros and I will investigate this further. It seems that both `ggplot2()` and `tidyverse()` are up to date with `CRAN` in our `conda` environment. Our sense is that this does not have to do with the `conda` build itself, but might have to do with an update to `rlang`, which relies on base `R`.

- When we freeze `R` at version `4.0` in the `conda` environment, `rlang` is version `1.0.6`.
- When we _do not_ freeze `R` at a particular version, we default to the latest (as of now, `R == 4.2`; `rlang == 1.1.1`).

The error is likely being thrown by a dependency from `rlang` which `tidyverse` relies upon, which is no longer being supported in `4.2`. A patch fix is to freeze `R` at `4.0`, but we want to ensure our setup works for the latest versions.

cc @gentzkow

**Comment by jc-cisneros** [comment]
@snairdesai I had some time to revisit this issue today. I rebuilt template using the yaml in [72204b6](https://github.com/gentzkow/template/commit/72204b62d06117c6a9940eb75137a133603a81c7) and got the same error 

```
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: NULL
  error: package or namespace load failed for ‘ggplot2’ in library.dynam(lib, package, package.lib):
 shared object ‘rlang.dylib’ not found
```

I eventually got the following message when I rebuilt the environment.
```
==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda
```

I updated conda (you can check your version with `conda -V`), rebuilt the environment from scratch using the yaml file on [72204b6](https://github.com/gentzkow/template/commit/72204b62d06117c6a9940eb75137a133603a81c7) and was able to load `tidyverse` without the previous issue:

```
(template) SIEPR-C02D90E2ML85:template jccp$ conda -V
conda 23.5.0
(template) SIEPR-C02D90E2ML85:template jccp$ R

R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(tidyverse)
── Attaching core tidyverse packages ─────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
```

R version 4.2.3 is now installed and that seems to fix the problem with the missing ` ‘rlang.dylib’`. I see on `conda-forge` that R-4.2 was updated 13 days ago; also flagging that R - 4.3 is now available but I assume the `template` environment is not using that version as other packages loaded as dependencies are likely not updated yet.

As a sanity check I completed a full run to have the versions log up to date in [3b0f388](https://github.com/gentzkow/template/commit/3b0f388ec0a09b0636f9369cdda97454ec265d8a). @snairdesai let me know if everything works on your end. If that is the case we can close this issue.

**Comment by snairdesai** [comment]
Thanks @jc-cisneros! Will test your solution as soon as I'm back.

**Comment by snairdesai** [comment]
@jc-cisneros I confirm that `template` runs as expected when using the solution outlined in https://github.com/gentzkow/template/issues/82#issuecomment-1614205766. I completed a full run in [`fb1e0ca`](https://github.com/gentzkow/template/commit/fb1e0caf3ccf93b9d84b7c44886051ceac6fdb08) to ensure stability. In [`49517dc`](https://github.com/gentzkow/template/commit/49517dc2ba37478961b1c1a58ad4b73720da1481), I proposed some minor edits to the `README.md` file ensuring users keep their `miniconda` installations up to date to prevent these errors.

I agree with you that this issue is good to close after a quick PR to bring the `README` edits back to `main`. However, I think this presents another reason to consider solutions distinct from `conda` if at all possible (as we have discussed). We can port further investigation to future issues.

Thanks for the work!

**Comment by jc-cisneros** [comment]
### Summary

In this issue we fixed the dependency issue with R described in https://github.com/gentzkow/template/issues/82#issue-1740530223. The solution was to update `conda` (more details in https://github.com/gentzkow/template/issues/82#issuecomment-1614205766).

The minor changes (updated README + logs) were brought to `master` in #83.
