### ISSUE TITLE
Solve chip confilct in `import.util` package

### ISSUE THREAD

**Issue by ShiqiYang2022** [gentzkow/template#89]
Follows https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009.

This issue aims to solve the conflict arising the from the Mac M2 chip on @snairdesai's local machine. The standard template run into an [error](https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009) in `import.util` package, and is no longer compiling on his updated conda environment local machine (though it did previously, and succeed on @jc-cisneros @ShiqiYang2022 end). 

This suggests `import.util` package was updated in the conda environment no longer supported by Apple Silicon. A hot fix which manually installed the `import.util` package to his local computer before building the conda environment worked. This issue aim to explore and compare other methods, currently the potential candidates includes: 

- Frozen the version of package in `conda_env.yaml`.
- Edit codes in `check_setup.py` and `run_all.py` to solve the conflict when compiling.

**Comment by ShiqiYang2022** [comment]
Per my investigation, I think it's rather a problem due to python package, instead of chips.

In Python versions `3.10.11+` through `3.12.0a7+`, `importlib.util` is not referenced in `importlib/__init__.py`, so by directly import `importlib`, it will throw an `AttributeError`. If you intend to use `importlib.util` in a regular Python environment, you should directly import `importlib.util` instead of trying to import `.util` from `importlib`. Details could be referred per threads [here](https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641).

I removed the conda env `template` on my local machine and re-run `template`. Initially I failed in the same error in https://github.com/gslab-econ/gslab_make/pull/65#issuecomment-1769271009. After I edit the code to import `importlib.util` directly, the `template` can successfully compiled again.

**Comment by ShiqiYang2022** [comment]
@snairdesai See this [comment](https://github.com/gentzkow/template/issues/89#issuecomment-1773559213), could you please edit `run_all.py` in the same commit f12dcd2 and re-construct the `template`? Once the template worked on your end, I will open a new pull request.

**Comment by snairdesai** [comment]
Will do!

**Comment by snairdesai** [comment]
@ShiqiYang2022 Confirming this ran on my end, great work! One comment, I am getting these odd warning lines in terminal when running this:

---

<img width="312" alt="Screenshot 2023-10-20 at 5 53 05 PM" src="https://github.com/gentzkow/template/assets/63830369/d6b1497a-eaca-482b-b640-bf616c9f5822">

---

<img width="423" alt="Screenshot 2023-10-20 at 5 53 20 PM" src="https://github.com/gentzkow/template/assets/63830369/03626fc9-7717-4e18-9053-dd413efa4a0c">

---

Do we think the way we are handling the escape characters might be linked to `importlib.util` in some way? Is this also appearing on your end?

cc @jc-cisneros

**Comment by ShiqiYang2022** [comment]
@snairdesai Thanks! Same warning on my end and I am investigating it!

**Comment by ShiqiYang2022** [comment]
@snairdesai Maybe give it another shot after a6f828c, I think per f12dcd2 we lose some function in original `importlib` but not in `importlib.util`. Thanks!

**Comment by snairdesai** [comment]
Looks perfect, thanks @ShiqiYang2022! Good to port to a PR -- feel free to assign me (I'll get to this sometime over the weekend).

**Comment by ShiqiYang2022** [comment]
### Summary

In this issue we fixed the error when running `import.util` package, described in https://github.com/gentzkow/template/issues/89#issue-1952943988. The solution was to import `import.util` directly instead import `.util` under the `importlib` module (more details in https://github.com/gentzkow/template/issues/89#issuecomment-1773559213).

The fixes were brought to `master` in #90. 

cc: @snairdesai @jc-cisneros
